language: php
php:
  - 7.4
  - 8.0
install: composer install
script: composer run ci && ./vendor/bin/phpunit --configuration phpunit.xml --coverage-text
notifications:
    email:
        - andrian@readdle.com
    on_success: never
    on_failure: always
